name: Deploy to UAT
on:
  pull_request:
    branches:
      - uat
jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snowflakedb/snowflake-cli-action@v1.5
      - name: Deploy SQL to UAT
        env:
          SNOWFLAKE_USER: ${{ secrets.UATD_SF_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.UATD_SF_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.UATD_SF_ACCOUNT }}
        run: |
          snow sql -f ./sql/ddl.sql
          snow sql -f ./sql/functions.sql
          snow sql -f ./sql/tasks.sql
