
-- Task to run the notebook every 5 minutes
CREATE OR REPLACE TASK RAW.GIT.RUN_FIRST_NOTEBOOK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
AS
    EXECUTE NOTEBOOK RAW.GIT.FIRST;

ALTER TASK RAW.GIT.RUN_FIRST_NOTEBOOK RESUME;

ALTER TASK RAW.GIT.RUN_FIRST_NOTEBOOK SUSPEND;
